### ISSUE TITLE
max() on empty sequence from array throws

### ISSUE THREAD

**Issue by vgpro54321** [arogozine/LinqToTypeScript#17]
Hello Guys,

IEnumerable<>.max() function in .NET returns null when sequence is empty (semantics maximum is unknown). LinqToTypeScript throws an error. Is this by design?

**Comment by vgpro54321** [comment]
Anybody alive?

**Comment by arogozine** [comment]
By the design.

See here,
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.max?view=net-6.0#system-linq-enumerable-max(system-collections-generic-ienumerable((system-int32)))

under exceptions,
It throws InvalidOperationException if 'source contains no elements'

Only outlier to that are nullable numeric types, but that type is not supported and would error out with TS strict mode.

**Comment by vgpro54321** [comment]
Make sense, thank you!
