### ISSUE TITLE
Unsupported engine for Node v16?

### ISSUE THREAD

**Issue by HadriMX** [arogozine/LinqToTypeScript#21]
When I install this package I get the following message:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'linq-to-typescript@10.0.0',
npm WARN EBADENGINE   required: { node: '>=17' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.1.2' }
npm WARN EBADENGINE }
```

I can't update to Node v17 so I was wondering whether it's really a problem or I can just ignore it?

Thank you for your work, btw :)

**Comment by arogozine** [comment]
I think it should still work with 16.

**Comment by michaelmairegger** [comment]
@arogozine It is still working but I prefer not to having such types of errors? Is there a reason why dev dependencies require on v17 instead of LTS version v16?

**Comment by arogozine** [comment]
You can use the previous until Node 18 comes out. I think 18 will be LTS.

Node 16 doesn't support `assert { type: "json" }` whereas Node 17 doesn't import JSON without it. So I went with the newer behavior for the [post build script](https://github.com/arogozine/LinqToTypeScript/blob/master/config/copy.js).
