### ISSUE TITLE
IEnumerable Min returns wrong result

### ISSUE THREAD

**Issue by HadriMX** [arogozine/LinqToTypeScript#22]
For some reason, min method in `IEnumerable<TSource>` returns a wrong result. You can see here, with this test that fails:

`
itEnumerable("Min", (asEnumerable) => {
        expect(asEnumerable([1, 2, 0, 1, 3, 4, 9, 8, 5]).min()).toBe(0)
    })
`

![image](https://user-images.githubusercontent.com/40123110/184418404-f5a4e210-afe9-42c5-b309-2c99003b3ca1.png)

**Comment by arogozine** [comment]
Considering this works for me and works for Azure Pipelines, I'm going to need more information,
![image](https://user-images.githubusercontent.com/7774690/184540636-9cb90714-f752-4fc9-9064-5b302550e632.png)

**Comment by HadriMX** [comment]
Sorry for the late response.
The test as they are do work, but I meant if you change [this test](https://github.com/arogozine/LinqToTypeScript/blob/master/tests/unittests/tests/Min.ts#L5) in particular to what I did in my screenshot, it will fail.

**Comment by arogozine** [comment]
Squeezed a fix into 11.0.0-beta release
