### ISSUE TITLE
Performance comparison/measurements

### ISSUE THREAD

**Issue by exactamente** [arogozine/LinqToTypeScript#23]
Hi guys,
First of all, many thanks for this library! I consider C# my 'native' programming language and was happy to discover your library. JS/TS lacks a lot of built-in capabilities, and libraries as yours help it to thrive.

However, I was wondering, do you have any perf tests to estimate influence of the library on the app performance?

Thanks again!

**Comment by exactamente** [comment]
UPD: wow, just checked, not 'guys', but @arogozine is soloing. Great job, man :)

**Comment by arogozine** [comment]
Haven't done benchmarks, plus as this library uses lazy evaluation (using yield), I'm not sure if there is a competitor to bench against.

I do accept PRs for performance and bug fixes though.
