### ISSUE TITLE
Support typescript 3.7

### ISSUE THREAD

**Issue by YacovGold** [arogozine/LinqToTypeScript#3]
Hi,

When upgrading to ts 3.7, the fallowing error occur
node_modules/linq-to-typescript/types/IParallelEnumerable.d.ts:1:148
TS2440: Import declaration conflicts with local declaration of 'IParallelEnumerable'.
If I remove the declaration, all is fine

Thanks

**Comment by arogozine** [comment]
I believe this is a circular reference to an interface which TS 3.7 is more picky about. Looking into this.

**Comment by arogozine** [comment]
@YacovGold Issue should be resolved in 6.0.1
